---@alias ListType
---| "eol"
---| "tab"
---| "space"
---| "multispace"
---| "lead"
---| "leadmultispace"
---| "trail"
---| "extends"
---| "precedes"
---| "conceal"
---| "nbsp"

---@class PluginConfig
---@field save_state boolean
---@field listchars table<ListType, string>
---@field exclude_filetypes string[]
